import type { Metadata } from "next";

import "../src/app/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export { default } from "@/app";
